# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from revent.v1 import control_pb2 as revent_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in revent/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlStub(object):
    """*
    Control provides bidirectional communication between clients and the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.stream_stream(
                '/revent.v1.Control/OpenSession',
                request_serializer=revent_dot_v1_dot_control__pb2.ClientToServerMessage.SerializeToString,
                response_deserializer=revent_dot_v1_dot_control__pb2.ServerToClientMessage.FromString,
                _registered_method=True)


class ControlServicer(object):
    """*
    Control provides bidirectional communication between clients and the server.
    """

    def OpenSession(self, request_iterator, context):
        """OpenSession opens a bidirectional stream between a client and the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSession': grpc.stream_stream_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=revent_dot_v1_dot_control__pb2.ClientToServerMessage.FromString,
                    response_serializer=revent_dot_v1_dot_control__pb2.ServerToClientMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'revent.v1.Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('revent.v1.Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """*
    Control provides bidirectional communication between clients and the server.
    """

    @staticmethod
    def OpenSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/revent.v1.Control/OpenSession',
            revent_dot_v1_dot_control__pb2.ClientToServerMessage.SerializeToString,
            revent_dot_v1_dot_control__pb2.ServerToClientMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
