# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: revent/v1/control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'revent/v1/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from revent.v1 import query_messages_pb2 as revent_dot_v1_dot_query__messages__pb2
from revent.v1 import event_messages_pb2 as revent_dot_v1_dot_event__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17revent/v1/control.proto\x12\trevent.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1erevent/v1/query_messages.proto\x1a\x1erevent/v1/event_messages.proto\"\xaa\x02\n\x15\x43lientToServerMessage\x12\x34\n\x0fregister_client\x18\x01 \x01(\x0b\x32\x19.revent.v1.RegisterClientH\x00\x12\x30\n\rquery_request\x18\x02 \x01(\x0b\x32\x17.revent.v1.QueryRequestH\x00\x12\x32\n\x0equery_response\x18\x03 \x01(\x0b\x32\x18.revent.v1.QueryResponseH\x00\x12?\n\x15register_source_event\x18\x04 \x01(\x0b\x32\x1e.revent.v1.RegisterSourceEventH\x00\x12)\n\theartbeat\x18\x05 \x01(\x0b\x32\x14.revent.v1.HeartbeatH\x00\x42\t\n\x07payload\"E\n\x0eRegisterClient\x12\x16\n\tclient_id\x18\x01 \x01(\tB\x03\xe0\x41\x02\x12\x1b\n\x0equery_handlers\x18\x02 \x03(\tB\x03\xe0\x41\x01\"\x0b\n\tHeartbeat\"\xf2\x03\n\x15ServerToClientMessage\x12\x38\n\x11\x63lient_registered\x18\x01 \x01(\x0b\x32\x1b.revent.v1.ClientRegisteredH\x00\x12\x34\n\x0fquery_requested\x18\x02 \x01(\x0b\x32\x19.revent.v1.QueryRequestedH\x00\x12\x34\n\x0fquery_responded\x18\x03 \x01(\x0b\x32\x19.revent.v1.QueryRespondedH\x00\x12)\n\theartbeat\x18\x04 \x01(\x0b\x32\x14.revent.v1.HeartbeatH\x00\x12G\n\x19\x63lient_registration_error\x18\x05 \x01(\x0b\x32\".revent.v1.ClientRegistrationErrorH\x00\x12?\n\x15query_requested_error\x18\x06 \x01(\x0b\x32\x1e.revent.v1.QueryRequestedErrorH\x00\x12\x43\n\x17source_event_registered\x18\x07 \x01(\x0b\x32 .revent.v1.SourceEventRegisteredH\x00\x12.\n\x0csource_event\x18\x08 \x01(\x0b\x32\x16.revent.v1.SourceEventH\x00\x42\t\n\x07payload\"%\n\x10\x43lientRegistered\x12\x11\n\tclient_id\x18\x01 \x01(\t\"<\n\x17\x43lientRegistrationError\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t2b\n\x07\x43ontrol\x12W\n\x0bOpenSession\x12 .revent.v1.ClientToServerMessage\x1a .revent.v1.ServerToClientMessage\"\x00(\x01\x30\x01\x42\x1b\n\trevent.v1B\x0c\x43ontrolProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'revent.v1.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\trevent.v1B\014ControlProtoP\001'
  _globals['_REGISTERCLIENT'].fields_by_name['client_id']._loaded_options = None
  _globals['_REGISTERCLIENT'].fields_by_name['client_id']._serialized_options = b'\340A\002'
  _globals['_REGISTERCLIENT'].fields_by_name['query_handlers']._loaded_options = None
  _globals['_REGISTERCLIENT'].fields_by_name['query_handlers']._serialized_options = b'\340A\001'
  _globals['_CLIENTTOSERVERMESSAGE']._serialized_start=136
  _globals['_CLIENTTOSERVERMESSAGE']._serialized_end=434
  _globals['_REGISTERCLIENT']._serialized_start=436
  _globals['_REGISTERCLIENT']._serialized_end=505
  _globals['_HEARTBEAT']._serialized_start=507
  _globals['_HEARTBEAT']._serialized_end=518
  _globals['_SERVERTOCLIENTMESSAGE']._serialized_start=521
  _globals['_SERVERTOCLIENTMESSAGE']._serialized_end=1019
  _globals['_CLIENTREGISTERED']._serialized_start=1021
  _globals['_CLIENTREGISTERED']._serialized_end=1058
  _globals['_CLIENTREGISTRATIONERROR']._serialized_start=1060
  _globals['_CLIENTREGISTRATIONERROR']._serialized_end=1120
  _globals['_CONTROL']._serialized_start=1122
  _globals['_CONTROL']._serialized_end=1220
# @@protoc_insertion_point(module_scope)
