# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: revent/v1/event_messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'revent/v1/event_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import field_info_pb2 as google_dot_api_dot_field__info__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1erevent/v1/event_messages.proto\x12\trevent.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x01\n\x13RegisterSourceEvent\x12\x1d\n\x08\x65vent_id\x18\x01 \x01(\tB\x0b\xe0\x41\x02\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x19\n\x0c\x61ggregate_id\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12\x1b\n\x0e\x61ggregate_type\x18\x03 \x01(\tB\x03\xe0\x41\x02\x12\x14\n\x07payload\x18\x04 \x01(\x0c\x42\x03\xe0\x41\x02\x12\x43\n\x08metadata\x18\x05 \x03(\x0b\x32,.revent.v1.RegisterSourceEvent.MetadataEntryB\x03\xe0\x41\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"T\n\x15SourceEventRegistered\x12\x1d\n\x08\x65vent_id\x18\x01 \x01(\tB\x0b\xe0\x41\x02\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x1c\n\x0fmonotonic_clock\x18\x02 \x01(\x04\x42\x03\xe0\x41\x02\"\xe0\x01\n\x0bSourceEvent\x12\x17\n\x02id\x18\x01 \x01(\tB\x0b\xe0\x41\x02\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x33\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x02\x12\x1c\n\x0fmonotonic_clock\x18\x03 \x01(\x04\x42\x03\xe0\x41\x02\x12\x1b\n\x0e\x61ggregate_type\x18\x04 \x01(\tB\x03\xe0\x41\x02\x12\x19\n\x0c\x61ggregate_id\x18\x05 \x01(\tB\x03\xe0\x41\x02\x12-\n\x07payload\x18\x06 \x01(\x0b\x32\x17.google.protobuf.StructB\x03\xe0\x41\x02\x42!\n\trevent.v1B\x12\x45ventMessagesProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'revent.v1.event_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\trevent.v1B\022EventMessagesProtoP\001'
  _globals['_REGISTERSOURCEEVENT_METADATAENTRY']._loaded_options = None
  _globals['_REGISTERSOURCEEVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['event_id']._loaded_options = None
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['event_id']._serialized_options = b'\340A\002\342\214\317\327\010\002\010\001'
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['aggregate_id']._loaded_options = None
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['aggregate_id']._serialized_options = b'\340A\002'
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['aggregate_type']._loaded_options = None
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['aggregate_type']._serialized_options = b'\340A\002'
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['payload']._loaded_options = None
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['payload']._serialized_options = b'\340A\002'
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['metadata']._loaded_options = None
  _globals['_REGISTERSOURCEEVENT'].fields_by_name['metadata']._serialized_options = b'\340A\001'
  _globals['_SOURCEEVENTREGISTERED'].fields_by_name['event_id']._loaded_options = None
  _globals['_SOURCEEVENTREGISTERED'].fields_by_name['event_id']._serialized_options = b'\340A\002\342\214\317\327\010\002\010\001'
  _globals['_SOURCEEVENTREGISTERED'].fields_by_name['monotonic_clock']._loaded_options = None
  _globals['_SOURCEEVENTREGISTERED'].fields_by_name['monotonic_clock']._serialized_options = b'\340A\002'
  _globals['_SOURCEEVENT'].fields_by_name['id']._loaded_options = None
  _globals['_SOURCEEVENT'].fields_by_name['id']._serialized_options = b'\340A\002\342\214\317\327\010\002\010\001'
  _globals['_SOURCEEVENT'].fields_by_name['created_at']._loaded_options = None
  _globals['_SOURCEEVENT'].fields_by_name['created_at']._serialized_options = b'\340A\002'
  _globals['_SOURCEEVENT'].fields_by_name['monotonic_clock']._loaded_options = None
  _globals['_SOURCEEVENT'].fields_by_name['monotonic_clock']._serialized_options = b'\340A\002'
  _globals['_SOURCEEVENT'].fields_by_name['aggregate_type']._loaded_options = None
  _globals['_SOURCEEVENT'].fields_by_name['aggregate_type']._serialized_options = b'\340A\002'
  _globals['_SOURCEEVENT'].fields_by_name['aggregate_id']._loaded_options = None
  _globals['_SOURCEEVENT'].fields_by_name['aggregate_id']._serialized_options = b'\340A\002'
  _globals['_SOURCEEVENT'].fields_by_name['payload']._loaded_options = None
  _globals['_SOURCEEVENT'].fields_by_name['payload']._serialized_options = b'\340A\002'
  _globals['_REGISTERSOURCEEVENT']._serialized_start=171
  _globals['_REGISTERSOURCEEVENT']._serialized_end=419
  _globals['_REGISTERSOURCEEVENT_METADATAENTRY']._serialized_start=372
  _globals['_REGISTERSOURCEEVENT_METADATAENTRY']._serialized_end=419
  _globals['_SOURCEEVENTREGISTERED']._serialized_start=421
  _globals['_SOURCEEVENTREGISTERED']._serialized_end=505
  _globals['_SOURCEEVENT']._serialized_start=508
  _globals['_SOURCEEVENT']._serialized_end=732
# @@protoc_insertion_point(module_scope)
