# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: revent/v1/query_messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'revent/v1/query_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import field_info_pb2 as google_dot_api_dot_field__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1erevent/v1/query_messages.proto\x12\trevent.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/field_info.proto\"\xbb\x01\n\x0cQueryRequest\x12\x1f\n\nrequest_id\x18\x01 \x01(\tB\x0b\xe0\x41\x02\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x15\n\x08query_id\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12@\n\nparameters\x18\x03 \x03(\x0b\x32\'.revent.v1.QueryRequest.ParametersEntryB\x03\xe0\x41\x01\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"E\n\rQueryResponse\x12\x1f\n\nrequest_id\x18\x01 \x01(\tB\x0b\xe0\x41\x02\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x13\n\x06result\x18\x02 \x01(\x0c\x42\x03\xe0\x41\x02\"\xba\x01\n\x0eQueryRequested\x12\x1f\n\nrequest_id\x18\x01 \x01(\tB\x0b\xe0\x41\x02\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x15\n\x08query_id\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12=\n\nparameters\x18\x03 \x03(\x0b\x32).revent.v1.QueryRequested.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"A\n\x0eQueryResponded\x12\x1f\n\nrequest_id\x18\x01 \x01(\tB\x0b\xe0\x41\x02\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x0e\n\x06result\x18\x02 \x01(\x0c\"b\n\x13QueryRequestedError\x12\x1f\n\nrequest_id\x18\x01 \x01(\tB\x0b\xe0\x41\x02\xe2\x8c\xcf\xd7\x08\x02\x08\x01\x12\x15\n\x08query_id\x18\x02 \x01(\tB\x03\xe0\x41\x02\x12\x13\n\x06reason\x18\x03 \x01(\tB\x03\xe0\x41\x02\x42!\n\trevent.v1B\x12QueryMessagesProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'revent.v1.query_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\trevent.v1B\022QueryMessagesProtoP\001'
  _globals['_QUERYREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_QUERYREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_QUERYREQUEST'].fields_by_name['request_id']._loaded_options = None
  _globals['_QUERYREQUEST'].fields_by_name['request_id']._serialized_options = b'\340A\002\342\214\317\327\010\002\010\001'
  _globals['_QUERYREQUEST'].fields_by_name['query_id']._loaded_options = None
  _globals['_QUERYREQUEST'].fields_by_name['query_id']._serialized_options = b'\340A\002'
  _globals['_QUERYREQUEST'].fields_by_name['parameters']._loaded_options = None
  _globals['_QUERYREQUEST'].fields_by_name['parameters']._serialized_options = b'\340A\001'
  _globals['_QUERYRESPONSE'].fields_by_name['request_id']._loaded_options = None
  _globals['_QUERYRESPONSE'].fields_by_name['request_id']._serialized_options = b'\340A\002\342\214\317\327\010\002\010\001'
  _globals['_QUERYRESPONSE'].fields_by_name['result']._loaded_options = None
  _globals['_QUERYRESPONSE'].fields_by_name['result']._serialized_options = b'\340A\002'
  _globals['_QUERYREQUESTED_PARAMETERSENTRY']._loaded_options = None
  _globals['_QUERYREQUESTED_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_QUERYREQUESTED'].fields_by_name['request_id']._loaded_options = None
  _globals['_QUERYREQUESTED'].fields_by_name['request_id']._serialized_options = b'\340A\002\342\214\317\327\010\002\010\001'
  _globals['_QUERYREQUESTED'].fields_by_name['query_id']._loaded_options = None
  _globals['_QUERYREQUESTED'].fields_by_name['query_id']._serialized_options = b'\340A\002'
  _globals['_QUERYRESPONDED'].fields_by_name['request_id']._loaded_options = None
  _globals['_QUERYRESPONDED'].fields_by_name['request_id']._serialized_options = b'\340A\002\342\214\317\327\010\002\010\001'
  _globals['_QUERYREQUESTEDERROR'].fields_by_name['request_id']._loaded_options = None
  _globals['_QUERYREQUESTEDERROR'].fields_by_name['request_id']._serialized_options = b'\340A\002\342\214\317\327\010\002\010\001'
  _globals['_QUERYREQUESTEDERROR'].fields_by_name['query_id']._loaded_options = None
  _globals['_QUERYREQUESTEDERROR'].fields_by_name['query_id']._serialized_options = b'\340A\002'
  _globals['_QUERYREQUESTEDERROR'].fields_by_name['reason']._loaded_options = None
  _globals['_QUERYREQUESTEDERROR'].fields_by_name['reason']._serialized_options = b'\340A\002'
  _globals['_QUERYREQUEST']._serialized_start=108
  _globals['_QUERYREQUEST']._serialized_end=295
  _globals['_QUERYREQUEST_PARAMETERSENTRY']._serialized_start=246
  _globals['_QUERYREQUEST_PARAMETERSENTRY']._serialized_end=295
  _globals['_QUERYRESPONSE']._serialized_start=297
  _globals['_QUERYRESPONSE']._serialized_end=366
  _globals['_QUERYREQUESTED']._serialized_start=369
  _globals['_QUERYREQUESTED']._serialized_end=555
  _globals['_QUERYREQUESTED_PARAMETERSENTRY']._serialized_start=246
  _globals['_QUERYREQUESTED_PARAMETERSENTRY']._serialized_end=295
  _globals['_QUERYRESPONDED']._serialized_start=557
  _globals['_QUERYRESPONDED']._serialized_end=622
  _globals['_QUERYREQUESTEDERROR']._serialized_start=624
  _globals['_QUERYREQUESTEDERROR']._serialized_end=722
# @@protoc_insertion_point(module_scope)
