---
name: release-please

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: googleapis/release-please-action@3ce3e46d5c374191edf61ba6c5d4b4d585b97e84 # v4.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
